// <auto-generated />
using System;
using EDennis.Samples.Hr.InternalApi2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDennis.Samples.Hr.InternalApi2.Migrations.FederalBackgroundCheck
{
    [DbContext(typeof(FederalBackgroundCheckContext))]
    partial class FederalBackgroundCheckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EDennis.Samples.Hr.InternalApi2.Models.FederalBackgroundCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("Status")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("FederalBackgroundCheck");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCompleted = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = "Pass"
                        },
                        new
                        {
                            Id = 2,
                            DateCompleted = new DateTime(2018, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = "Pass"
                        },
                        new
                        {
                            Id = 3,
                            DateCompleted = new DateTime(2018, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = "Fail"
                        },
                        new
                        {
                            Id = 4,
                            DateCompleted = new DateTime(2018, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = "Pass"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
