// <auto-generated />
using System;
using EDennis.Samples.Colors.InternalApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDennis.Samples.Colors.InternalApi.Migrations.ColorHistoryDb
{
    [DbContext(typeof(ColorHistoryDbContext))]
    partial class ColorHistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EDennis.Samples.Colors.InternalApi.Models.Color", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("SysStart");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<DateTime>("SysEnd");

                    b.Property<string>("SysUser");

                    b.Property<string>("SysUserNext");

                    b.HasKey("Id", "SysStart");

                    b.ToTable("Color","dbo_history");
                });
#pragma warning restore 612, 618
        }
    }
}
