// <auto-generated />
using EDennis.Samples.DbContextConfigsApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDennis.Samples.DbContextConfigsApi.Lib.Migrations.DbContext2Migrations
{
    [DbContext(typeof(DbContext2))]
    [Migration("20191216105240_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("EDennis.Samples.DbContextConfigsApi.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SysUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Moe",
                            SysUser = "jack@hill.org"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Larry",
                            SysUser = "jill@hill.org"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Curly",
                            SysUser = "jack@hill.org"
                        });
                });

            modelBuilder.Entity("EDennis.Samples.DbContextConfigsApi.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SysUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SysUser = "jill@hill.org",
                            Title = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            SysUser = "jack@hill.org",
                            Title = "Employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
