// file generated by EDennis.DataScaffolder
// using connection string(s) from appsettings.Development.json
namespace EDennis.Samples.Colors.InternalApi.Models {
    public static partial class ColorDbContextDataFactory {
        public static Color[] ColorRecords { get; set; }
            = new Color[] {
                new Color {
                        Id = 1,
                        Name = "black",
                },
                new Color {
                        Id = 2,
                        Name = "white",
                },
                new Color {
                        Id = 3,
                        Name = "gray",
                },
                new Color {
                        Id = 4,
                        Name = "red",
                },
                new Color {
                        Id = 5,
                        Name = "green",
                },
                new Color {
                        Id = 6,
                        Name = "blue",
                },
            };
    }
}
