// <auto-generated />
using System;
using EDennis.Samples.InternalApi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDennis.Samples.InternalApi1.Seq.Migrations
{
    [DbContext(typeof(HrContext))]
    [Migration("20181119080841_HrContext_Initial")]
    partial class HrContext_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.seqEmployee", "'seqEmployee', '', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:.seqPosition", "'seqPosition', '', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EDennis.Samples.InternalApi1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for seqEmployee");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(convert(datetime2,'9999-12-31 23:59:59.9999999'))");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new { Id = 1, FirstName = "Bob", SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 2, FirstName = "Monty", SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 3, FirstName = "Drew", SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 4, FirstName = "Wayne", SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });

            modelBuilder.Entity("EDennis.Samples.InternalApi1.Models.EmployeePosition", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<int>("PositionId");

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(convert(datetime2,'9999-12-31 23:59:59.9999999'))");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("EmployeeId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("EmployeePosition");

                    b.HasData(
                        new { EmployeeId = 1, PositionId = 1, SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { EmployeeId = 2, PositionId = 1, SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { EmployeeId = 3, PositionId = 2, SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { EmployeeId = 4, PositionId = 2, SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });

            modelBuilder.Entity("EDennis.Samples.InternalApi1.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for seqPosition");

                    b.Property<bool>("IsManager");

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(convert(datetime2,'9999-12-31 23:59:59.9999999'))");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new { Id = 1, IsManager = true, SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Game Show Manager" },
                        new { Id = 2, IsManager = false, SysEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), SysStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Game Show Host" }
                    );
                });

            modelBuilder.Entity("EDennis.Samples.InternalApi1.Models.EmployeePosition", b =>
                {
                    b.HasOne("EDennis.Samples.InternalApi1.Models.Employee", "Employee")
                        .WithMany("EmployeePositions")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_EmployeePosition_Employee")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EDennis.Samples.InternalApi1.Models.Position", "Position")
                        .WithMany("EmployeePositions")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("fk_EmployeePosition_Position")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
