// <auto-generated />
using EDennis.Samples.ScopedLogging.ColorsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDennis.Samples.ScopedLogging.ColorsApi.Migrations
{
    [DbContext(typeof(ColorDbContext))]
    [Migration("20191004083334_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("EDennis.Samples.ScopedLogging.ColorsApi.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Red")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Blue = 0,
                            Green = 0,
                            Name = "Black",
                            Red = 0
                        },
                        new
                        {
                            Id = 2,
                            Blue = 255,
                            Green = 255,
                            Name = "White",
                            Red = 255
                        },
                        new
                        {
                            Id = 3,
                            Blue = 127,
                            Green = 127,
                            Name = "Grey",
                            Red = 127
                        },
                        new
                        {
                            Id = 4,
                            Blue = 0,
                            Green = 0,
                            Name = "Red",
                            Red = 255
                        },
                        new
                        {
                            Id = 5,
                            Blue = 0,
                            Green = 255,
                            Name = "Green",
                            Red = 0
                        },
                        new
                        {
                            Id = 6,
                            Blue = 255,
                            Green = 0,
                            Name = "Blue",
                            Red = 0
                        },
                        new
                        {
                            Id = 7,
                            Blue = 0,
                            Green = 255,
                            Name = "Yellow",
                            Red = 255
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
